-- Marks listings whose seoTitle/seoDescription were generated by scripts/commerce/apply-seo.ts (so regeneration never overwrites manual text).
-- Metadata-only change on PostgreSQL 11+ (constant default). Applied manually:
--   docker exec -i agency-os-postgres psql -U agency_os -d agency_os < packages/db/prisma/sql/commerce_listing_seo_auto.sql
-- Rollback of the generated texts: UPDATE "CommerceListing" SET "seoTitle" = NULL, "seoDescription" = NULL, "seoAuto" = false WHERE "seoAuto";
ALTER TABLE "CommerceListing" ADD COLUMN IF NOT EXISTS "seoAuto" BOOLEAN NOT NULL DEFAULT false;
