/**
 * EN → RO product name translation with persistent cache (CommerceTranslation).
 *
 * - Source texts are hashed (md5 of lower-cased text) so Postgres can join on md5(lower(nameEn)).
 * - Missing translations are generated by the configured LLM in batches with a fixed glossary.
 * - Manual edits (source = 'manual') are never overwritten.
 */
import { createHash } from 'crypto'
import { db } from '@repo/db'

const GEMINI_BASE = 'https://generativelanguage.googleapis.com/v1beta/models'

function models(): string[] {
  const primary = process.env.COMMERCE_TRANSLATE_MODEL || 'gemini-flash-lite-latest'
  return [...new Set([primary, 'gemini-flash-lite-latest', 'gemini-flash-latest'])]
}

/** Direct REST call so we can disable "thinking" (big latency win for simple translation). */
async function geminiJson(model: string, system: string, user: string): Promise<string> {
  const key = process.env.GEMINI_API_KEY
  if (!key) throw new Error('GEMINI_API_KEY is not configured')
  if (!/^[a-z0-9.-]+$/.test(model)) throw new Error('Invalid model name')
  const res = await fetch(`${GEMINI_BASE}/${model}:generateContent`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json', 'x-goog-api-key': key },
    signal: AbortSignal.timeout(90_000),
    body: JSON.stringify({
      systemInstruction: { parts: [{ text: system }] },
      contents: [{ role: 'user', parts: [{ text: user }] }],
      generationConfig: {
        temperature: 0,
        maxOutputTokens: 8192,
        responseMimeType: 'application/json',
        thinkingConfig: { thinkingLevel: /lite/.test(model) ? 'minimal' : 'low' },
      },
    }),
  })
  if (!res.ok) {
    const body = await res.text().catch(() => '')
    const quota = res.status === 429 && /quota/i.test(body)
    throw new Error(`Gemini ${model} ${res.status}${quota ? ' quota-exhausted' : ''} ${body.slice(0, 160).replace(/\s+/g, ' ')}`)
  }
  const data = (await res.json()) as { candidates?: { content?: { parts?: { text?: string }[] } }[] }
  return data.candidates?.[0]?.content?.parts?.map((p) => p.text ?? '').join('') ?? ''
}

const sleep = (ms: number) => new Promise((r) => setTimeout(r, ms))

export function textHash(s: string): string {
  return createHash('md5').update(s.toLowerCase()).digest('hex')
}

const GLOSSARY = `
FRONT=față, REAR=spate, LEFT/LE=stânga, RIGHT/RI=dreapta, UPPER=superior, LOWER=inferior, INNER=interior, OUTER=exterior
BUMPER=bară, FRONT BUMPER=bară față, BUMPER GRILLE=grilă bară, BUMPER REINFORCEMENT=armătură bară, BUMPER BRACKET=suport bară
FENDER=aripă, INNER PLASTIC FENDER=carenaj aripă, FENDER FLARE=bandou aripă, HOOD=capotă motor, TAIL GATE=haion, DOOR=ușă, SILL=prag
GRILLE=grilă, FRONT PANEL=trager, HEAD LAMP=far, TAIL LAMP=stop, FOG LAMP=proiector, SIDE LAMP=semnalizare, LICENCE PLATE LAMP=lampă număr
DOOR MIRROR=oglindă, MIRROR GLASS=sticlă oglindă, MIRROR COVER=capac oglindă, HEATED=încălzit(ă), ELECTRICAL=electric(ă), FOLDABLE=rabatabil(ă)
PRIMED=grunduit(ă), CHROME=cromat, CONVEX GLASS=sticlă convexă, ASPHERICAL GLASS=sticlă asferică
WINDOW REGULATOR=macara geam, W/O MOTOR=fără motor, DOOR HANDLE=mâner ușă, DOOR LOCK=broască ușă, CENTRAL LOCK=închidere centralizată, DOOR CHECK=limitator ușă, HINGE=balama
GAS SPRING=amortizor (telescop), RADIATOR=radiator, CONDENSER=condensator AC, COOLING FAN=electroventilator, HEATER RADIATOR=radiator încălzire, AUXILIARY TANK=vas expansiune
WIPER WASHER TANK=vas lichid parbriz, PDC=senzori parcare, W/2 PDC=cu 2 găuri senzori parcare, FOG LAMP HOLE=găuri proiectoare, WASHER HOLES=găuri spălătoare faruri
SPLASH PANEL BRAKE DISC=protecție disc frână, ENGINE COVER=scut motor, TOW HOOK COVER=capac cârlig remorcare, A QUALITY=calitate A, W/=cu, W/O=fără
WHEEL ARCH=pasaj roată, EXH=țeavă de eșapament (2SINGLE EXH=2 țevi eșapament simple, 2 DOUBLE EXH=2 țevi eșapament duble), MOULDING=bandă ornamentală, BUMPER ABSORBER=absorbant impact bară
`.trim()

const SYSTEM = `Ești traducător specializat în piese auto pentru un magazin online din România.
Tradu denumirile de produse din engleză în română, natural, cum le-ar căuta un client român.
Reguli:
- Folosește glosarul de mai jos pentru consecvență.
- Păstrează neschimbate: mărci (DEPO, TYC, VALEO, HELLA, MARELLI, NRF…), coduri, numere, dimensiuni, unități, tipuri de becuri (H7, H11, LED), denumiri de echipare (M-SPORT, AMG-LINE, S-LINE).
- Acordă adjectivele corect în gen (ex. „Bară față grunduită”, „Far electric”).
- Prima literă majusculă, restul cu litere mici (exceptând mărci/coduri). Folosește diacritice (ă, â, î, ș, ț).
- Numerele lipite de cuvinte (ex. 2SINGLE, 4WD, 5D) se păstrează ca atare sau se despart corect; nu lipi cifre de litere românești.
- Nu adăuga informații noi. Nu traduce în paranteză decât conținutul existent.
Glosar:
${GLOSSARY}
Răspunde STRICT cu JSON: {"t": ["traducere1", "traducere2", ...]} în aceeași ordine și cu același număr de elemente.`

export async function translateBatch(texts: string[]): Promise<string[]> {
  const numbered = texts.map((t, i) => `${i + 1}. ${t}`).join('\n')
  let lastErr: unknown
  for (const model of models()) {
    for (let attempt = 0; attempt < 3; attempt++) {
      try {
        const content = await geminiJson(model, SYSTEM, `Tradu cele ${texts.length} denumiri:\n${numbered}`)
        const match = content.match(/\{[\s\S]*\}/)
        const out = match ? (JSON.parse(match[0]) as { t?: unknown[] }) : null
        if (!Array.isArray(out?.t) || out.t.length !== texts.length) {
          throw new Error(`Translation batch size mismatch (${out?.t?.length} vs ${texts.length})`)
        }
        return out.t.map((s) => String(s).trim().slice(0, 300))
      } catch (e) {
        lastErr = e
        const msg = e instanceof Error ? e.message : String(e)
        if (/quota-exhausted/.test(msg)) break // daily quota: try the next model
        const transient = /\b(429|500|502|503|504)\b|overloaded|high demand|mismatch|JSON|timeout|aborted|fetch failed/i.test(msg)
        if (!transient) break
        await sleep(2000 * (attempt + 1) ** 2)
      }
    }
  }
  throw lastErr instanceof Error ? lastErr : new Error(String(lastErr))
}

/** Untranslated = nameRo missing, or just the untouched English copy with no source recorded. */
export async function applyCachedTranslations(): Promise<number> {
  return db.$executeRaw`
    UPDATE "CommerceProduct" p
    SET "nameRo" = t."text", "nameRoSource" = t."source", "updatedAt" = now()
    FROM "CommerceTranslation" t
    WHERE (p."nameRo" IS NULL OR (p."nameRoSource" IS NULL AND p."nameRo" = p."nameEn"))
      AND t."targetLang" = 'ro' AND t."hash" = md5(lower(p."nameEn"))`
}

/**
 * Translate distinct untranslated product names. Resumable: run repeatedly until `remaining` is 0.
 */
export async function translatePendingNames(opts: { limit?: number; batchSize?: number; concurrency?: number } = {}) {
  const limit = opts.limit ?? 2000
  const batchSize = opts.batchSize ?? 60
  const concurrency = opts.concurrency ?? 3

  await applyCachedTranslations()

  const pending = await db.$queryRaw<{ nameEn: string }[]>`
    SELECT DISTINCT p."nameEn" FROM "CommerceProduct" p
    WHERE p."isActive" = true AND (p."nameRo" IS NULL OR (p."nameRoSource" IS NULL AND p."nameRo" = p."nameEn"))
    ORDER BY p."nameEn"
    LIMIT ${limit}`
  const texts = pending.map((r) => r.nameEn)

  const batches: string[][] = []
  for (let i = 0; i < texts.length; i += batchSize) batches.push(texts.slice(i, i + batchSize))

  let translated = 0
  const errors: string[] = []
  let idx = 0
  async function worker() {
    while (idx < batches.length) {
      const batch = batches[idx++]!
      try {
        const ro = await translateBatch(batch)
        await db.commerceTranslation.createMany({
          data: batch.map((src, i) => ({ hash: textHash(src), sourceText: src, text: ro[i]!, source: 'ai' })),
          skipDuplicates: true,
        })
        translated += batch.length
      } catch (e) {
        errors.push(e instanceof Error ? e.message : String(e))
      }
    }
  }
  await Promise.all(Array.from({ length: concurrency }, worker))
  const applied = await applyCachedTranslations()

  const rows = await db.$queryRaw<{ count: bigint }[]>`
    SELECT COUNT(DISTINCT "nameEn")::bigint AS count FROM "CommerceProduct" p WHERE "isActive" = true AND (p."nameRo" IS NULL OR (p."nameRoSource" IS NULL AND p."nameRo" = p."nameEn"))`
  return { requested: texts.length, translated, applied, remaining: Number(rows[0]?.count ?? 0), errors: errors.slice(0, 5) }
}
