import type { Client } from './types'

// ─── CLIENȚI FINALI (income) ───────────────────
export const clientsFinalClimaticPRO: Client[] = [
  {
    id: 'cp-c01',
    businessLine: 'climaticpro',
    entityType: 'end_clients',
    companyName: 'Maria Ionescu',
    cui: '',
    contactPerson: 'Maria Ionescu',
    email: 'maria.ionescu@gmail.com',
    phone: '+40 744 100 200',
    status: 'activ',
    industry: 'Rezidențial',
    address: 'Str. Aviatorilor 15, București, Sector 1',
    monthlyRevenue: 0,
    contractStartDate: '2026-03-15',
    services: ['AC Split 12000 BTU — Daikin FTXF35A'],
    notes: 'Instalare completată. Garanție 3 ani.',
    createdAt: '2026-03-10',
  },
  {
    id: 'cp-c02',
    businessLine: 'climaticpro',
    entityType: 'end_clients',
    companyName: 'SC Biroul Verde SRL',
    cui: 'RO39876543',
    contactPerson: 'Andrei Dumitrescu',
    email: 'andrei@biroulverde.ro',
    phone: '+40 722 300 400',
    status: 'activ',
    industry: 'Office',
    address: 'Bd. Unirii 22, București, Sector 3',
    monthlyRevenue: 0,
    contractStartDate: '2026-04-01',
    services: ['Multi-split 4 unități — Gree Lomo'],
    notes: 'Birou open space. 4 unități interioare. Programat instalare.',
    createdAt: '2026-03-25',
  },
  {
    id: 'cp-c03',
    businessLine: 'climaticpro',
    entityType: 'end_clients',
    companyName: 'Pavel Gheorghe',
    cui: '',
    contactPerson: 'Pavel Gheorghe',
    email: 'pavel.g@yahoo.com',
    phone: '+40 756 500 600',
    status: 'activ',
    industry: 'Rezidențial',
    address: 'Str. Primăverii 8, Cluj-Napoca',
    monthlyRevenue: 0,
    contractStartDate: '2026-02-20',
    services: ['Pompă de Căldură — Midea M-Thermal'],
    notes: 'Casă nouă. Instalare pompă de căldură aer-apă.',
    createdAt: '2026-02-15',
  },
  {
    id: 'cp-c04',
    businessLine: 'climaticpro',
    entityType: 'end_clients',
    companyName: 'Restaurant Bella Vista',
    cui: 'RO42345678',
    contactPerson: 'Luca Marinescu',
    email: 'luca@bellavista.ro',
    phone: '+40 733 700 800',
    status: 'activ',
    industry: 'HoReCa',
    address: 'Piața Sfatului 3, Brașov',
    monthlyRevenue: 0,
    contractStartDate: '2026-03-01',
    services: ['AC Duct comercial — Daikin FBQ'],
    notes: 'Restaurant, 2 unități AC duct + ventilație.',
    createdAt: '2026-02-25',
  },
  {
    id: 'cp-c05',
    businessLine: 'climaticpro',
    entityType: 'end_clients',
    companyName: 'Elena Vasilescu',
    cui: '',
    contactPerson: 'Elena Vasilescu',
    email: 'elena.v@gmail.com',
    phone: '+40 768 900 100',
    status: 'prospect',
    industry: 'Rezidențial',
    address: 'Str. Republicii 45, Timișoara',
    monthlyRevenue: 0,
    contractStartDate: '',
    services: [],
    notes: 'Cerere nouă. Apartament 3 camere, nevoie 2 split-uri.',
    createdAt: '2026-04-05',
  },
  {
    id: 'cp-c06',
    businessLine: 'climaticpro',
    entityType: 'end_clients',
    companyName: 'SC Digital Space SRL',
    cui: 'RO40567890',
    contactPerson: 'Marius Popescu',
    email: 'marius@digitalspace.ro',
    phone: '+40 745 200 300',
    status: 'activ',
    industry: 'IT',
    address: 'Str. Fabricii 12, Iași',
    monthlyRevenue: 0,
    contractStartDate: '2026-01-10',
    services: ['AC Multi-split 3 unități — Midea Aurora'],
    notes: 'Server room + 2 birouri. Mentenanță inclusă.',
    createdAt: '2026-01-05',
  },
]

// ─── INSTALATORI (expense) ─────────────────────
export const instalatoriClimaticPRO: Client[] = [
  {
    id: 'cp-i01',
    businessLine: 'climaticpro',
    entityType: 'installers',
    companyName: 'Ion Popescu — PFA',
    cui: 'RO1234567890',
    contactPerson: 'Ion Popescu',
    email: 'ion.popescu@gmail.com',
    phone: '+40 744 111 222',
    status: 'activ',
    industry: 'HVAC',
    address: 'București, Sector 4',
    monthlyRevenue: -1200,
    contractStartDate: '2025-06-01',
    services: ['Instalare AC', 'Mentenanță'],
    rating: 4.8,
    certificari: 'Autorizat ISCIR, Daikin Certified',
    zonaAcoperire: 'București, Ilfov',
    nrInstalari: 142,
    notes: 'Top installer. Disponibil L-V, ocazional Sâmbăta.',
    createdAt: '2025-05-20',
  },
  {
    id: 'cp-i02',
    businessLine: 'climaticpro',
    entityType: 'installers',
    companyName: 'Cool Install SRL',
    cui: 'RO38765432',
    contactPerson: 'Radu Munteanu',
    email: 'radu@coolinstall.ro',
    phone: '+40 722 333 444',
    status: 'activ',
    industry: 'HVAC',
    address: 'Cluj-Napoca',
    monthlyRevenue: -800,
    contractStartDate: '2025-09-01',
    services: ['Instalare AC', 'Pompe de căldură'],
    rating: 4.5,
    certificari: 'Autorizat ISCIR',
    zonaAcoperire: 'Cluj, Sibiu, Alba',
    nrInstalari: 89,
    notes: 'Echipă de 3 persoane. Bun pe pompe de căldură.',
    createdAt: '2025-08-15',
  },
  {
    id: 'cp-i03',
    businessLine: 'climaticpro',
    entityType: 'installers',
    companyName: 'Clima Expert SRL',
    cui: 'RO37654321',
    contactPerson: 'Mihai Stoica',
    email: 'mihai@climaexpert.ro',
    phone: '+40 733 555 666',
    status: 'activ',
    industry: 'HVAC',
    address: 'Timișoara',
    monthlyRevenue: -600,
    contractStartDate: '2025-11-01',
    services: ['Instalare AC', 'Ventilație', 'Centrale termice'],
    rating: 4.9,
    certificari: 'Autorizat ISCIR, Gree Partner, Midea Certified',
    zonaAcoperire: 'Timiș, Arad, Caraș-Severin',
    nrInstalari: 67,
    notes: 'Rating excelent. Specializat pe comercial+rezidențial.',
    createdAt: '2025-10-20',
  },
  {
    id: 'cp-i04',
    businessLine: 'climaticpro',
    entityType: 'installers',
    companyName: 'AC Service Brașov SRL',
    cui: 'RO36543210',
    contactPerson: 'Dan Vlad',
    email: 'dan@acservicebrasov.ro',
    phone: '+40 755 777 888',
    status: 'activ',
    industry: 'HVAC',
    address: 'Brașov',
    monthlyRevenue: -400,
    contractStartDate: '2026-01-15',
    services: ['Instalare AC'],
    rating: 4.2,
    certificari: 'Autorizat ISCIR',
    zonaAcoperire: 'Brașov, Covasna',
    nrInstalari: 34,
    notes: 'Nou pe platformă. Feedback bun până acum.',
    createdAt: '2026-01-10',
  },
]

// ─── FURNIZORI MATERIALE (expense) ─────────────
export const furnizoriClimaticPRO: Client[] = [
  {
    id: 'cp-s01',
    businessLine: 'climaticpro',
    entityType: 'suppliers',
    companyName: 'Daikin România SRL',
    cui: 'RO12345678',
    contactPerson: 'Alexandru Preda',
    email: 'alexandru.preda@daikin.ro',
    phone: '+40 21 300 4000',
    status: 'activ',
    industry: 'Distribuitor HVAC',
    website: 'https://daikin.ro',
    address: 'Bd. Timișoara 104, București',
    monthlyRevenue: -8500,
    contractStartDate: '2025-03-01',
    services: ['AC Split', 'AC Multi-split', 'AC Duct', 'Pompe de căldură'],
    produse: 'Daikin FTXF, FBQ, Altherma',
    termenPlata: 30,
    discountNegociat: 22,
    notes: 'Distribuitor oficial Daikin. Termen 30 zile, discount 22%.',
    createdAt: '2025-02-15',
  },
  {
    id: 'cp-s02',
    businessLine: 'climaticpro',
    entityType: 'suppliers',
    companyName: 'Gree Distribution SRL',
    cui: 'RO23456789',
    contactPerson: 'Cristina Moldovan',
    email: 'cristina@greedistribution.ro',
    phone: '+40 21 400 5000',
    status: 'activ',
    industry: 'Distribuitor HVAC',
    address: 'Str. Industriilor 88, București',
    monthlyRevenue: -5200,
    contractStartDate: '2025-06-01',
    services: ['AC Split', 'AC Multi-split'],
    produse: 'Gree Lomo, Fairy, U-Crown',
    termenPlata: 14,
    discountNegociat: 18,
    notes: 'Stoc bun pe modele entry-level. Termen scurt 14 zile.',
    createdAt: '2025-05-20',
  },
  {
    id: 'cp-s03',
    businessLine: 'climaticpro',
    entityType: 'suppliers',
    companyName: 'Midea Parts SRL',
    cui: 'RO34567890',
    contactPerson: 'Vlad Enescu',
    email: 'vlad@mideaparts.ro',
    phone: '+40 31 200 3000',
    status: 'activ',
    industry: 'Distribuitor HVAC',
    address: 'Str. Fabricii 22, Ploiești',
    monthlyRevenue: -3100,
    contractStartDate: '2025-09-01',
    services: ['Pompe de căldură', 'AC Split'],
    produse: 'Midea Aurora, M-Thermal, Mission',
    termenPlata: 21,
    discountNegociat: 15,
    notes: 'Specializat pompe de căldură. Livrare rapidă.',
    createdAt: '2025-08-15',
  },
]
