import type { Client } from './types'

export const clientsFudly: Client[] = [
  {
    id: 'fud-001',
    businessLine: 'fudly',
    entityType: 'restaurants',
    companyName: 'Restaurant La Giovanni',
    cui: 'RO41234567',
    contactPerson: 'Giovanni Rossi',
    email: 'giovanni@lagiovanni.ro',
    phone: '+40 721 100 200',
    status: 'activ',
    industry: 'HoReCa',
    website: 'https://lagiovanni.ro',
    address: 'Str. Lipsani 12, București',
    monthlyRevenue: 99,
    contractStartDate: '2025-11-01',
    services: ['Comenzi Online', 'Meniu Digital'],
    plan: 'Premium (99€)',
    activeOrders: 840,
    notes: 'Primul restaurant onboardat. Toate funcțiile active.',
    createdAt: '2025-10-20',
  },
  {
    id: 'fud-002',
    businessLine: 'fudly',
    entityType: 'restaurants',
    companyName: 'Trattoria Roma',
    cui: 'RO43567890',
    contactPerson: 'Marco Bianchi',
    email: 'marco@trattoriaroma.ro',
    phone: '+40 745 300 400',
    status: 'activ',
    industry: 'HoReCa',
    address: 'Str. Napoca 8, Cluj-Napoca',
    monthlyRevenue: 49,
    contractStartDate: '2026-01-15',
    services: ['Comenzi Online'],
    plan: 'Standard (49€)',
    activeOrders: 520,
    notes: 'Restaurant italian popular в Cluj. Plan Standard.',
    createdAt: '2026-01-10',
  },
  {
    id: 'fud-003',
    businessLine: 'fudly',
    entityType: 'restaurants',
    companyName: 'Sushi Master',
    cui: 'RO44890123',
    contactPerson: 'Yuki Tanaka',
    email: 'yuki@sushimaster.ro',
    phone: '+40 733 500 600',
    status: 'prospect',
    industry: 'HoReCa',
    address: 'Bd. Revoluției 15, Timișoara',
    monthlyRevenue: 0,
    contractStartDate: '',
    services: [],
    plan: 'Trial',
    activeOrders: 0,
    notes: 'În trial 14 zile. Interesat de Premium.',
    createdAt: '2026-04-01',
  },
  {
    id: 'fud-004',
    businessLine: 'fudly',
    entityType: 'restaurants',
    companyName: 'Burger Joint',
    cui: 'RO45123456',
    contactPerson: 'Alex Marinescu',
    email: 'alex@burgerjoint.ro',
    phone: '+40 756 700 800',
    status: 'prospect',
    industry: 'HoReCa',
    address: 'Str. Palat 3, Iași',
    monthlyRevenue: 0,
    contractStartDate: '',
    services: [],
    plan: 'Onboarding',
    notes: 'Menu setup în progres. Onboarding estimat 5 zile.',
    createdAt: '2026-03-28',
  },
  {
    id: 'fud-005',
    businessLine: 'fudly',
    entityType: 'restaurants',
    companyName: 'Casa Veche',
    cui: 'RO42345678',
    contactPerson: 'Ion Gheorghe',
    email: 'ion@casaveche.ro',
    phone: '+40 744 900 100',
    status: 'activ',
    industry: 'HoReCa',
    website: 'https://casaveche.ro',
    address: 'Str. Republicii 22, Brașov',
    monthlyRevenue: 99,
    contractStartDate: '2025-12-01',
    services: ['Comenzi Online', 'Meniu Digital', 'Analytics'],
    plan: 'Premium (99€)',
    activeOrders: 670,
    notes: 'Restaurant tradițional românesc. Toate funcțiile active.',
    createdAt: '2025-11-25',
  },
  {
    id: 'fud-006',
    businessLine: 'fudly',
    entityType: 'restaurants',
    companyName: 'Pizzeria Napoli',
    cui: 'RO46456789',
    contactPerson: 'Luigi Ferrara',
    email: 'luigi@pizzerianapoli.ro',
    phone: '+40 768 200 300',
    status: 'activ',
    industry: 'HoReCa',
    address: 'Bd. Mamaia 45, Constanța',
    monthlyRevenue: 49,
    contractStartDate: '2025-09-01',
    services: ['Comenzi Online'],
    plan: 'Standard (49€)',
    activeOrders: 120,
    notes: '⚠️ Comenzi în scădere. Posibil churn risk.',
    createdAt: '2025-08-20',
  },
  {
    id: 'fud-007',
    businessLine: 'fudly',
    entityType: 'restaurants',
    companyName: 'Bistro Central',
    cui: 'RO47789012',
    contactPerson: 'Elena Dragomir',
    email: 'elena@bistrocentral.ro',
    phone: '+40 731 400 500',
    status: 'activ',
    industry: 'HoReCa',
    address: 'Piața Mare 5, Sibiu',
    monthlyRevenue: 29,
    contractStartDate: '2026-02-01',
    services: ['Comenzi Online'],
    plan: 'Basic (29€)',
    activeOrders: 210,
    notes: 'Bistro mic, plan Basic. Potențial upgrade.',
    createdAt: '2026-01-28',
  },
  {
    id: 'fud-008',
    businessLine: 'fudly',
    entityType: 'restaurants',
    companyName: 'Wok Express',
    cui: 'RO48012345',
    contactPerson: 'Chen Wei',
    email: 'chen@wokexpress.ro',
    phone: '+40 755 600 700',
    status: 'prospect',
    industry: 'HoReCa',
    address: 'Bd. Unirii 88, București',
    monthlyRevenue: 0,
    contractStartDate: '',
    services: [],
    plan: 'Trial',
    notes: 'Trial început pe 5 aprilie. Rezultate promițătoare.',
    createdAt: '2026-04-05',
  },
]
