import type { Client } from './types'

export const clients: Client[] = [
  {
    id: 'cli-001',
    businessLine: 'agency',
    entityType: 'clients',
    companyName: 'MARYSTELV S.R.L.',
    cui: 'RO16261002',
    regCom: 'J40/13962/2018',
    contactPerson: 'Isabela Tihu',
    email: 'office@qualitycontrol.com.ro',
    phone: '+4 0786 335 876',
    status: 'activ',
    industry: 'Quality Assurance & Audit',
    website: 'https://qualitycontrol.com.ro',
    address: 'Str. Burnitei, Nr.24, Biroul 138, Et.1, Sector 3, București',
    monthlyRevenue: 0,
    contractStartDate: '',
    services: ['SEO Programmatic', 'Web Development', 'Google Ads'],
    notes: 'Proiect flagship QualityControl.com.ro. SEO programmatic pe piața nordică. Ofertă în curs.',
    createdAt: '2025-07-20'
  },
  {
    id: 'cli-002',
    businessLine: 'agency',
    entityType: 'clients',
    companyName: 'Fudly Technologies SRL',
    cui: 'RO42156789',
    regCom: 'J40/5678/2019',
    contactPerson: 'Andrei Popescu',
    email: 'andrei@fudly.ro',
    phone: '+40 721 345 678',
    status: 'activ',
    industry: 'FoodTech & Delivery',
    website: 'https://fudly.ro',
    address: 'Bd. Unirii 22, București',
    monthlyRevenue: 2400,
    contractStartDate: '2025-03-15',
    services: ['SEO Programmatic', 'Web Development', 'Mentenanță'],
    notes: 'Platformă de food delivery. SEO programmatic pentru restaurante partenere.',
    createdAt: '2025-03-10'
  },
  {
    id: 'cli-003',
    businessLine: 'agency',
    entityType: 'clients',
    companyName: 'ClimaticPRO SRL',
    cui: 'RO35678901',
    regCom: 'J12/3456/2015',
    contactPerson: 'Marius Ionescu',
    email: 'marius@climaticpro.ro',
    phone: '+40 745 890 123',
    status: 'activ',
    industry: 'HVAC & Climatizare',
    website: 'https://climaticpro.ro',
    address: 'Str. Fabricii 12, Brașov',
    monthlyRevenue: 1800,
    contractStartDate: '2025-09-01',
    services: ['Google Ads', 'SEO', 'Web Development'],
    notes: 'Campanii Google Ads agresive. Focus pe lead generation B2C.',
    createdAt: '2025-08-25'
  },
  {
    id: 'cli-004',
    businessLine: 'agency',
    entityType: 'clients',
    companyName: 'WertAudit SRL',
    cui: 'RO29087654',
    regCom: 'J40/7890/2012',
    contactPerson: 'Diana Constantinescu',
    email: 'diana@wertaudit.ro',
    phone: '+40 733 456 789',
    status: 'activ',
    industry: 'Audit & Consultanță ISO',
    website: 'https://wertaudit.ro',
    address: 'Str. Victoriei 88, București',
    monthlyRevenue: 1500,
    contractStartDate: '2025-06-01',
    services: ['Web Development', 'SEO'],
    notes: 'Firmă de audit ISO. Site nou + SEO. Potențial de upsell pe Ads.',
    createdAt: '2025-05-20'
  },
  {
    id: 'cli-005',
    businessLine: 'agency',
    entityType: 'clients',
    companyName: 'Swiss Amanet SRL',
    cui: 'RO38754120',
    regCom: 'J40/2345/2017',
    contactPerson: 'Peter Müller',
    email: 'peter@swissamanet.ch',
    phone: '+41 44 234 56 78',
    status: 'activ',
    industry: 'Financial Services',
    website: 'https://swissamanet.ch',
    address: 'Bahnhofstrasse 42, Zürich',
    monthlyRevenue: 4800,
    contractStartDate: '2025-02-01',
    services: ['SEO', 'Google Ads', 'Web Development'],
    notes: 'Client elvețian premium. Campanii multilingve (DE/FR/IT). Buget mare pe Ads.',
    createdAt: '2025-01-20'
  },
  {
    id: 'cli-006',
    businessLine: 'agency',
    entityType: 'clients',
    companyName: 'NordFinance Group SA',
    cui: 'DK-31254789',
    regCom: 'CVR-31254789',
    contactPerson: 'Lars Andersson',
    email: 'lars@nordfinance.dk',
    phone: '+45 22 34 56 78',
    status: 'activ',
    industry: 'Finance & Banking',
    website: 'https://nordfinance.dk',
    address: 'Kongens Nytorv 8, Copenhagen',
    monthlyRevenue: 5200,
    contractStartDate: '2025-07-01',
    services: ['SEO Programmatic', 'Google Ads'],
    notes: 'Client nordic. SEO în limba daneză. Cel mai mare buget pe Ads.',
    createdAt: '2025-06-20'
  },
  {
    id: 'cli-007',
    businessLine: 'agency',
    entityType: 'clients',
    companyName: 'Meridian Logistics SA',
    cui: 'RO29087654',
    regCom: 'J40/4567/2010',
    contactPerson: 'Cristian Dumitrescu',
    email: 'cristian.d@meridianlog.ro',
    phone: '+40 733 456 789',
    status: 'activ',
    industry: 'Transport & Logistics',
    website: 'https://meridianlogistics.ro',
    address: 'Șos. Giurgiului 120, București',
    monthlyRevenue: 4500,
    contractStartDate: '2024-11-01',
    services: ['SEO Programmatic', 'Web Development', 'Mentenanță'],
    notes: 'SEO programmatic pentru 200+ rute de transport.',
    createdAt: '2024-10-15'
  },
  {
    id: 'cli-008',
    businessLine: 'agency',
    entityType: 'clients',
    companyName: 'Dental Excellence Group',
    cui: 'RO43210987',
    regCom: 'J40/8901/2018',
    contactPerson: 'Dr. Maria Ionescu',
    email: 'maria@dentalexcellence.ro',
    phone: '+40 745 890 123',
    status: 'activ',
    industry: 'Healthcare & Medical',
    website: 'https://dentalexcellence.ro',
    address: 'Bd. Aviatorilor 15, București',
    monthlyRevenue: 2800,
    contractStartDate: '2025-06-01',
    services: ['SEO', 'Web Development'],
    notes: 'Focus pe SEO local pentru 3 clinici din București.',
    createdAt: '2025-05-20'
  },
  {
    id: 'cli-009',
    businessLine: 'agency',
    entityType: 'clients',
    companyName: 'Carpathian Adventures SRL',
    cui: 'RO42109876',
    regCom: 'J08/1234/2016',
    contactPerson: 'Mihai Stanciu',
    email: 'mihai@carpathianadv.ro',
    phone: '+40 712 567 890',
    status: 'activ',
    industry: 'Tourism & Hospitality',
    website: 'https://carpathianadventures.ro',
    address: 'Str. Poiana Narciselor 5, Brașov',
    monthlyRevenue: 2100,
    contractStartDate: '2025-04-01',
    services: ['SEO', 'Web Development'],
    notes: 'Turism activ, focus pe piața DACH.',
    createdAt: '2025-03-28'
  },
  {
    id: 'cli-010',
    businessLine: 'agency',
    entityType: 'clients',
    companyName: 'AutoService Pro SRL',
    cui: 'RO39876543',
    regCom: 'J40/6789/2014',
    contactPerson: 'Bogdan Radu',
    email: 'bogdan@autoservicepro.ro',
    phone: '+40 744 678 901',
    status: 'inactiv',
    industry: 'Automotive',
    website: 'https://autoservicepro.ro',
    address: 'Str. Industriilor 33, Ploiești',
    monthlyRevenue: 0,
    contractStartDate: '2024-06-01',
    services: ['Web Development'],
    notes: 'Contract expirat în decembrie 2024. Posibilitate de reînnoire.',
    createdAt: '2024-05-15'
  },
  {
    id: 'cli-011',
    businessLine: 'agency',
    entityType: 'clients',
    companyName: 'EduSmart Academy SRL',
    cui: 'RO40987654',
    regCom: 'J40/2345/2020',
    contactPerson: 'Ana Popa',
    email: 'ana@edusmart.ro',
    phone: '+40 731 890 123',
    status: 'prospect',
    industry: 'Education & Training',
    website: 'https://edusmart.ro',
    address: 'Str. Academiei 20, București',
    monthlyRevenue: 0,
    contractStartDate: '',
    services: [],
    notes: 'Interesat de platformă de cursuri online. Încă în discuții.',
    createdAt: '2026-01-10'
  },
  {
    id: 'cli-012',
    businessLine: 'agency',
    entityType: 'clients',
    companyName: 'Metro Design Studio SRL',
    cui: 'RO38901234',
    regCom: 'J40/3456/2018',
    contactPerson: 'Vlad Enescu',
    email: 'vlad@metrodesign.ro',
    phone: '+40 755 234 678',
    status: 'prospect',
    industry: 'Design & Architecture',
    website: 'https://metrodesign.ro',
    address: 'Str. Arhitecților 7, Timișoara',
    monthlyRevenue: 0,
    contractStartDate: '',
    services: [],
    notes: 'A cerut ofertă pentru redesign site + SEO. Trimis propunerea.',
    createdAt: '2026-03-01'
  }
]
