import type { Invoice } from './types'

export const invoices: Invoice[] = [
  {
    id: 'inv-001',
    businessLine: 'agency',
    entityType: 'clients',
    clientId: 'cli-001',
    number: 'ASNS-2026-001',
    status: 'platita',
    type: 'fiscala',
    direction: 'emisa' as const,
    amount: 3800,
    currency: 'EUR',
    issuedDate: '2026-03-01',
    dueDate: '2026-03-15',
    paidDate: '2026-03-12',
    description: 'Servicii SEO Programmatic + Web Dev — Martie 2026',
    items: [
      { description: 'SEO Programmatic Nordic', quantity: 1, unitPrice: 2200 },
      { description: 'Mentenanță & Updates Website', quantity: 1, unitPrice: 600 },
      { description: 'Google Ads Management', quantity: 1, unitPrice: 1000 },
    ]
  },
  {
    id: 'inv-002',
    businessLine: 'agency',
    entityType: 'clients',
    clientId: 'cli-005',
    number: 'ASNS-2026-002',
    status: 'platita',
    type: 'fiscala',
    direction: 'emisa' as const,
    amount: 4800,
    currency: 'EUR',
    issuedDate: '2026-03-01',
    dueDate: '2026-03-15',
    paidDate: '2026-03-14',
    description: 'Servicii SEO + Google Ads — Swiss Amanet — Martie 2026',
    items: [
      { description: 'SEO Multilanguage (DE/FR/IT)', quantity: 1, unitPrice: 2800 },
      { description: 'Google Ads Management CH', quantity: 1, unitPrice: 2000 },
    ]
  },
  {
    id: 'inv-003',
    businessLine: 'agency',
    entityType: 'clients',
    clientId: 'cli-006',
    number: 'ASNS-2026-003',
    status: 'trimisa',
    type: 'fiscala',
    direction: 'emisa' as const,
    amount: 5200,
    currency: 'EUR',
    issuedDate: '2026-04-01',
    dueDate: '2026-04-15',
    description: 'Servicii SEO Programmatic + Ads — NordFinance — Aprilie 2026',
    items: [
      { description: 'SEO Programmatic Daneza', quantity: 1, unitPrice: 3200 },
      { description: 'Google Ads Management DK', quantity: 1, unitPrice: 2000 },
    ]
  },
  {
    id: 'inv-004',
    businessLine: 'agency',
    entityType: 'clients',
    clientId: 'cli-002',
    number: 'ASNS-2026-004',
    status: 'trimisa',
    type: 'fiscala',
    direction: 'emisa' as const,
    amount: 2400,
    currency: 'EUR',
    issuedDate: '2026-04-01',
    dueDate: '2026-04-15',
    description: 'Servicii SEO Programmatic + Mentenanță — Fudly — Aprilie 2026',
    items: [
      { description: 'SEO Programmatic', quantity: 1, unitPrice: 1800 },
      { description: 'Mentenanță Web', quantity: 1, unitPrice: 600 },
    ]
  },
  {
    id: 'inv-005',
    businessLine: 'agency',
    entityType: 'clients',
    clientId: 'cli-003',
    number: 'ASNS-2026-005',
    status: 'emisa',
    type: 'proforma',
    direction: 'emisa' as const,
    amount: 1800,
    currency: 'EUR',
    issuedDate: '2026-04-05',
    dueDate: '2026-04-20',
    description: 'Google Ads Management + SEO — ClimaticPRO — Aprilie 2026',
    items: [
      { description: 'Google Ads Management', quantity: 1, unitPrice: 1000 },
      { description: 'SEO On-Page', quantity: 1, unitPrice: 800 },
    ]
  },
  {
    id: 'inv-006',
    businessLine: 'agency',
    entityType: 'clients',
    clientId: 'cli-007',
    number: 'ASNS-2026-006',
    status: 'restanta',
    type: 'fiscala',
    direction: 'emisa' as const,
    amount: 4500,
    currency: 'EUR',
    issuedDate: '2026-02-01',
    dueDate: '2026-02-15',
    description: 'SEO Programmatic + Mentenanță — Meridian Logistics — Februarie 2026',
    items: [
      { description: 'SEO Programmatic Rute', quantity: 1, unitPrice: 3500 },
      { description: 'Mentenanță Web', quantity: 1, unitPrice: 500 },
      { description: 'Hosting & Suport', quantity: 1, unitPrice: 500 },
    ]
  },
  {
    id: 'inv-007',
    businessLine: 'agency',
    entityType: 'clients',
    clientId: 'cli-008',
    number: 'ASNS-2026-007',
    status: 'restanta',
    type: 'fiscala',
    direction: 'emisa' as const,
    amount: 2800,
    currency: 'EUR',
    issuedDate: '2026-03-01',
    dueDate: '2026-03-15',
    description: 'SEO Local + Web Dev — Dental Excellence — Martie 2026',
    items: [
      { description: 'SEO Local 3 Clinici', quantity: 1, unitPrice: 1800 },
      { description: 'Web Development Updates', quantity: 1, unitPrice: 1000 },
    ]
  },
  {
    id: 'inv-008',
    businessLine: 'agency',
    entityType: 'clients',
    clientId: 'cli-004',
    number: 'ASNS-2026-008',
    status: 'platita',
    type: 'fiscala',
    direction: 'emisa' as const,
    amount: 1500,
    currency: 'EUR',
    issuedDate: '2026-03-01',
    dueDate: '2026-03-20',
    paidDate: '2026-03-18',
    description: 'SEO + Web Dev — WertAudit — Martie 2026',
    items: [
      { description: 'SEO On-Page & Technical', quantity: 1, unitPrice: 800 },
      { description: 'Web Development', quantity: 1, unitPrice: 700 },
    ]
  },
]
