import type { Lead } from './types'

export const leadsClimaticPRO: Lead[] = [
  // ─── End Clients pipeline ───
  { id: 'cpl-001', businessLine: 'climaticpro', entityType: 'end_clients', companyName: 'Elena Vasilescu', contactPerson: 'Elena Vasilescu', email: 'elena.v@gmail.com', phone: '+40 768 900 100', status: 'cerere', source: 'website', estimatedValue: 1800, probability: 30, priority: 'medium', assignedTo: 'Alexandru', nextAction: 'Trimite ofertă', nextActionDate: '2026-04-12', notes: 'Apartament 3 camere, 2 split-uri Daikin.', createdAt: '2026-04-05', updatedAt: '2026-04-08' },
  { id: 'cpl-002', businessLine: 'climaticpro', entityType: 'end_clients', companyName: 'SC Biroul Verde SRL', contactPerson: 'Andrei Dumitrescu', email: 'andrei@biroulverde.ro', phone: '+40 722 300 400', status: 'oferta_cp', source: 'google_ads', estimatedValue: 4200, probability: 60, priority: 'high', assignedTo: 'Alexandru', nextAction: 'Confirmare preț', nextActionDate: '2026-04-11', notes: '4 unități Gree multi-split. Au acceptat oferta 80%.', createdAt: '2026-03-25', updatedAt: '2026-04-09' },
  { id: 'cpl-003', businessLine: 'climaticpro', entityType: 'end_clients', companyName: 'Hotel Belvedere SRL', contactPerson: 'Cristina Popa', email: 'cristina@hotelbelvedere.ro', phone: '+40 744 500 600', status: 'programat', source: 'referral', estimatedValue: 8500, probability: 90, priority: 'high', assignedTo: 'Alexandru', nextAction: 'Instalare pe 15 Apr', nextActionDate: '2026-04-15', notes: '8 unități AC cameră hotel. Instalator: Ion Popescu PFA.', createdAt: '2026-03-10', updatedAt: '2026-04-09' },
  { id: 'cpl-004', businessLine: 'climaticpro', entityType: 'end_clients', companyName: 'Maria Ionescu', contactPerson: 'Maria Ionescu', email: 'maria.ionescu@gmail.com', phone: '+40 744 100 200', status: 'instalat', source: 'website', estimatedValue: 1500, probability: 100, priority: 'low', assignedTo: 'Alexandru', notes: 'Daikin FTXF35A instalat pe 15 Mar. Garanție activată.', createdAt: '2026-03-10', updatedAt: '2026-03-15' },

  // ─── Installers pipeline ───
  { id: 'cpl-005', businessLine: 'climaticpro', entityType: 'installers', companyName: 'Vlad Termoclima PFA', contactPerson: 'Vlad Iorga', email: 'vlad@termoclima.ro', phone: '+40 755 100 200', status: 'aplicat_inst', source: 'website', estimatedValue: 0, probability: 40, priority: 'medium', assignedTo: 'Andrei', nextAction: 'Verificare documente ISCIR', nextActionDate: '2026-04-14', notes: 'Aplicație nouă. Experiență 5 ani. Zonă: Constanța.', createdAt: '2026-04-07', updatedAt: '2026-04-08' },
  { id: 'cpl-006', businessLine: 'climaticpro', entityType: 'installers', companyName: 'FrigoTech SRL', contactPerson: 'George Enache', email: 'george@frigotech.ro', phone: '+40 733 200 300', status: 'verificat_inst', source: 'referral', estimatedValue: 0, probability: 75, priority: 'high', assignedTo: 'Andrei', nextAction: 'Instalare test', nextActionDate: '2026-04-13', notes: 'Referral de la Cool Install. 3 tehnicieni. Zonă: Oradea.', createdAt: '2026-03-28', updatedAt: '2026-04-09' },

  // ─── Suppliers pipeline ───
  { id: 'cpl-007', businessLine: 'climaticpro', entityType: 'suppliers', companyName: 'Samsung Climate Solutions', contactPerson: 'Ana Preda', email: 'ana.preda@samsung.com', phone: '+40 21 600 7000', status: 'negociere_fz', source: 'cold_outreach', estimatedValue: 0, probability: 50, priority: 'medium', assignedTo: 'Alexandru', nextAction: 'Negociere discount volum', nextActionDate: '2026-04-16', notes: 'Samsung WindFree. Se discută discount 20% pt volum >50 unit/an.', createdAt: '2026-03-15', updatedAt: '2026-04-08' },
]
