import type { Lead } from './types'

export const leadsFudly: Lead[] = [
  { id: 'flead-001', businessLine: 'fudly', entityType: 'restaurants', companyName: 'Sushi Master', contactPerson: 'Yuki Tanaka', email: 'yuki@sushimaster.ro', phone: '+40 733 500 600', status: 'trial', source: 'marketplace', estimatedValue: 99, probability: 40, priority: 'medium', assignedTo: 'Andrei', nextAction: 'Check-in trial — zi 10', nextActionDate: '2026-04-14', notes: 'Trial activ 14 zile. Interesat de Premium.', createdAt: '2026-04-01', updatedAt: '2026-04-08' },
  { id: 'flead-002', businessLine: 'fudly', entityType: 'restaurants', companyName: 'Burger Joint', contactPerson: 'Alex Marinescu', email: 'alex@burgerjoint.ro', phone: '+40 756 700 800', status: 'onboarding', source: 'referral', estimatedValue: 49, probability: 75, priority: 'high', assignedTo: 'Alexandru', nextAction: 'Finalizare setup meniu', nextActionDate: '2026-04-11', notes: 'Referral de la Casa Veche. Menu setup în progres.', createdAt: '2026-03-28', updatedAt: '2026-04-09' },
  { id: 'flead-003', businessLine: 'fudly', entityType: 'restaurants', companyName: 'Wok Express', contactPerson: 'Chen Wei', email: 'chen@wokexpress.ro', phone: '+40 755 600 700', status: 'trial', source: 'website', estimatedValue: 49, probability: 35, priority: 'medium', assignedTo: 'Andrei', nextAction: 'Email cu tutorial video', nextActionDate: '2026-04-12', notes: 'Trial început recent. A configurat meniul parțial.', createdAt: '2026-04-05', updatedAt: '2026-04-10' },
  { id: 'flead-004', businessLine: 'fudly', entityType: 'restaurants', companyName: 'Pizzeria Napoli', contactPerson: 'Luigi Ferrara', email: 'luigi@pizzerianapoli.ro', phone: '+40 768 200 300', status: 'churn_risk', source: 'partner', estimatedValue: 49, probability: 30, priority: 'urgent', assignedTo: 'Alexandru', nextAction: 'Apel de retentie — oferă discount', nextActionDate: '2026-04-10', notes: 'Comenzi în scădere 60% luna aceasta. Risc mare de churn.', createdAt: '2025-08-20', updatedAt: '2026-04-09' },
  { id: 'flead-005', businessLine: 'fudly', entityType: 'restaurants', companyName: 'Grill House Mamaia', contactPerson: 'Radu Constantescu', email: 'radu@grillhouse.ro', phone: '+40 744 100 200', status: 'activ_fudly', source: 'marketplace', estimatedValue: 99, probability: 100, priority: 'low', assignedTo: 'Alexandru', notes: 'Activ de 3 luni. 400+ comenzi/lună. Stabil.', createdAt: '2026-01-10', updatedAt: '2026-04-01' },
]
