import type { Lead } from './types'

export const leads: Lead[] = [
  { id: 'lead-001', businessLine: 'agency', entityType: 'clients', companyName: 'Apex Industrial SRL', contactPerson: 'Gheorghe Ionescu', email: 'gheorghe@apexindustrial.ro', phone: '+40 721 111 222', status: 'contactat', source: 'website', estimatedValue: 2400, probability: 20, priority: 'medium', assignedTo: 'Alexandru', nextAction: 'Apel inițial de calificare', nextActionDate: '2026-04-12', createdAt: '2026-04-08', updatedAt: '2026-04-08' },
  { id: 'lead-002', businessLine: 'agency', entityType: 'clients', companyName: 'Nordic Shipping AS', contactPerson: 'Erik Johansen', email: 'erik@nordicshipping.no', phone: '+47 22 33 44 55', status: 'calificat', source: 'linkedin', estimatedValue: 6500, probability: 45, priority: 'high', assignedTo: 'Andrei', nextAction: 'Programat demo al platformei', nextActionDate: '2026-04-14', notes: 'Interesat de SEO programmatic pentru rute maritime.', createdAt: '2026-04-01', updatedAt: '2026-04-09' },
  { id: 'lead-003', businessLine: 'agency', entityType: 'clients', companyName: 'FinServ Capital SRL', contactPerson: 'Mircea Petrescu', email: 'mircea@finservcapital.ro', phone: '+40 744 333 444', status: 'oferta_trimisa', source: 'referral', estimatedValue: 3800, probability: 55, priority: 'high', assignedTo: 'Alexandru', nextAction: 'Follow-up pe oferta trimisă', nextActionDate: '2026-04-11', notes: 'Referral de la MARYSTELV. Nevoie urgentă de website nou.', createdAt: '2026-03-25', updatedAt: '2026-04-07' },
  { id: 'lead-004', businessLine: 'agency', entityType: 'clients', companyName: 'Bucharest Legal Partners', contactPerson: 'Avocata Simona Pop', email: 'simona@blpartners.ro', phone: '+40 731 555 666', status: 'negociere', source: 'google_ads', estimatedValue: 2200, probability: 70, priority: 'urgent', assignedTo: 'Andrei', nextAction: 'Negociere finală contract', nextActionDate: '2026-04-10', notes: 'Avocatură. Vor site + SEO local pentru 2 parteneri.', createdAt: '2026-03-15', updatedAt: '2026-04-09' },
  { id: 'lead-005', businessLine: 'agency', entityType: 'clients', companyName: 'CleanPro Services SRL', contactPerson: 'Ion Matei', email: 'ion@cleanpro.ro', status: 'contactat', source: 'website', estimatedValue: 1200, probability: 15, priority: 'low', assignedTo: 'Alexandru', nextAction: 'Email introductiv', nextActionDate: '2026-04-13', createdAt: '2026-04-09', updatedAt: '2026-04-09' },
  { id: 'lead-006', businessLine: 'agency', entityType: 'clients', companyName: 'Danske Vinduer ApS', contactPerson: 'Morten Christensen', email: 'morten@danskevinduer.dk', phone: '+45 55 66 77 88', status: 'castigat', source: 'cold_outreach', estimatedValue: 4200, probability: 100, priority: 'high', assignedTo: 'Andrei', notes: 'Contract semnat! Web dev + SEO. Start proiect luna aceasta.', createdAt: '2026-02-20', updatedAt: '2026-04-05' },
  { id: 'lead-007', businessLine: 'agency', entityType: 'clients', companyName: 'Mountain Resort Brașov SRL', contactPerson: 'Tudor Petre', email: 'tudor@mountainresort.ro', phone: '+40 756 777 888', status: 'pierdut', source: 'website', estimatedValue: 3000, probability: 0, priority: 'medium', assignedTo: 'Alexandru', notes: 'Au ales alt furnizor. Preț mai mic dar calitate inferioară.', createdAt: '2026-01-10', updatedAt: '2026-03-20' },
  { id: 'lead-008', businessLine: 'agency', entityType: 'clients', companyName: 'OptiVet Clinics SRL', contactPerson: 'Dr. Raluca Stoica', email: 'raluca@optivet.ro', phone: '+40 768 888 999', status: 'calificat', source: 'referral', estimatedValue: 1800, probability: 35, priority: 'medium', assignedTo: 'Alexandru', nextAction: 'Follow-up după ce verifică bugetul', nextActionDate: '2026-04-15', notes: 'Lanț de clinici veterinare. Referral de la Dental Excellence.', createdAt: '2026-04-03', updatedAt: '2026-04-08' },
  { id: 'lead-009', businessLine: 'agency', entityType: 'clients', companyName: 'Stockholm Fintech AB', contactPerson: 'Anna Lindqvist', email: 'anna@stockholmfintech.se', phone: '+46 70 123 45 67', status: 'negociere', source: 'cold_outreach', estimatedValue: 7200, probability: 60, priority: 'urgent', assignedTo: 'Andrei', nextAction: 'Call final de negociere', nextActionDate: '2026-04-11', notes: 'Cel mai mare deal potențial. SEO + Ads pe piața suedeză.', createdAt: '2026-02-28', updatedAt: '2026-04-09' },
  { id: 'lead-010', businessLine: 'agency', entityType: 'clients', companyName: 'GastroDeluxe SRL', contactPerson: 'Chef Iulian Munteanu', email: 'iulian@gastrodeluxe.ro', phone: '+40 745 333 444', status: 'contactat', source: 'referral', estimatedValue: 2600, probability: 25, priority: 'high', assignedTo: 'Andrei', nextAction: 'Apel de prezentare', nextActionDate: '2026-04-11', notes: 'Restaurant fine dining. Referral de la client existent.', createdAt: '2026-04-10', updatedAt: '2026-04-10' },
  { id: 'lead-011', businessLine: 'agency', entityType: 'clients', companyName: 'Bavarian Motors Service GmbH', contactPerson: 'Klaus Weber', email: 'klaus@bavarianmotors.de', phone: '+49 89 123 456 78', status: 'oferta_trimisa', source: 'referral', estimatedValue: 6000, probability: 50, priority: 'urgent', assignedTo: 'Andrei', nextAction: 'Aprobare buget cu management-ul', nextActionDate: '2026-04-13', notes: 'Service auto premium. Referral de la Swiss Amanet. Piața DACH.', createdAt: '2026-02-10', updatedAt: '2026-04-09' },
  { id: 'lead-012', businessLine: 'agency', entityType: 'clients', companyName: 'Nordic Textile Import AB', contactPerson: 'Sofia Bergström', email: 'sofia@nordictextile.se', phone: '+46 73 456 78 90', status: 'oferta_trimisa', source: 'linkedin', estimatedValue: 4800, probability: 55, priority: 'high', assignedTo: 'Andrei', nextAction: 'Revizuire contract final', nextActionDate: '2026-04-12', notes: 'Import textile din Asia. Vor SEO programmatic pe piața nordică.', createdAt: '2026-02-15', updatedAt: '2026-04-08' },
  { id: 'lead-013', businessLine: 'agency', entityType: 'clients', companyName: 'TechnoMed Devices SRL', contactPerson: 'Dr. Victor Moldoveanu', email: 'victor@technomed.ro', phone: '+40 721 555 666', status: 'contactat', source: 'google_ads', estimatedValue: 4000, probability: 15, priority: 'high', assignedTo: 'Andrei', nextAction: 'Apel de calificare', nextActionDate: '2026-04-14', notes: 'Dispozitive medicale. Piață de nișă cu potențial ridicat.', createdAt: '2026-04-10', updatedAt: '2026-04-10' },
  { id: 'lead-014', businessLine: 'agency', entityType: 'clients', companyName: 'Rapid Courier Services SRL', contactPerson: 'Dan Voicu', email: 'dan@rapidcourier.ro', phone: '+40 733 111 222', status: 'castigat', source: 'referral', estimatedValue: 2800, probability: 100, priority: 'medium', assignedTo: 'Alexandru', notes: 'Website nou + SEO. A semnat contractul, onboarding în curs.', createdAt: '2026-03-01', updatedAt: '2026-04-02' },
  { id: 'lead-015', businessLine: 'agency', entityType: 'clients', companyName: 'Casa Moderna Imobiliare SRL', contactPerson: 'Cristina Barbu', email: 'cristina@casamoderna.ro', phone: '+40 767 444 555', status: 'calificat', source: 'website', estimatedValue: 3200, probability: 45, priority: 'medium', assignedTo: 'Alexandru', nextAction: 'Pregătire propunere detaliată', nextActionDate: '2026-04-13', notes: 'Agenție imobiliară, 50+ proprietăți. Nevoie de SEO local.', createdAt: '2026-03-18', updatedAt: '2026-04-06' },
]
