import type { Project } from './types'

export const projects: Project[] = [
  {
    id: 'proj-001',
    businessLine: 'agency',
    entityType: 'clients',
    clientId: 'cli-001',
    name: 'Redesign Site QualityControl',
    type: 'website',
    status: 'in_lucru',
    progress: 45,
    startDate: '2026-02-01',
    deadline: '2026-05-15',
    budget: 8500,
    hoursEstimated: 120,
    hoursLogged: 54,
    teamMembers: ['Alexandru', 'Maria']
  },
  {
    id: 'proj-002',
    businessLine: 'agency',
    entityType: 'clients',
    clientId: 'cli-002',
    name: 'SEO Programmatic Fudly',
    type: 'seo_programmatic',
    status: 'in_lucru',
    progress: 72,
    startDate: '2025-01-15',
    deadline: '2026-06-30',
    budget: 18000,
    hoursEstimated: 240,
    hoursLogged: 185,
    teamMembers: ['Andrei', 'Alexandru', 'Maria']
  },
  {
    id: 'proj-003',
    businessLine: 'agency',
    entityType: 'clients',
    clientId: 'cli-003',
    name: 'Google Ads ClimaticPRO',
    type: 'google_ads',
    status: 'in_lucru',
    progress: 60,
    startDate: '2025-10-01',
    deadline: '2026-09-30',
    budget: 12000,
    hoursEstimated: 150,
    hoursLogged: 92,
    teamMembers: ['Andrei']
  },
  {
    id: 'proj-004',
    businessLine: 'agency',
    entityType: 'clients',
    clientId: 'cli-004',
    name: 'Audit ISO & Site WertAudit',
    type: 'website',
    status: 'review',
    progress: 88,
    startDate: '2025-07-01',
    deadline: '2026-04-30',
    budget: 7000,
    hoursEstimated: 100,
    hoursLogged: 92,
    teamMembers: ['Alexandru', 'Maria']
  },
  {
    id: 'proj-005',
    businessLine: 'agency',
    entityType: 'clients',
    clientId: 'cli-001',
    name: 'SEO Programmatic QualityControl Nordic',
    type: 'seo_programmatic',
    status: 'in_lucru',
    progress: 38,
    startDate: '2025-09-01',
    deadline: '2026-08-31',
    budget: 22000,
    hoursEstimated: 300,
    hoursLogged: 114,
    teamMembers: ['Andrei', 'Alexandru']
  },
  {
    id: 'proj-006',
    businessLine: 'agency',
    entityType: 'clients',
    clientId: 'cli-005',
    name: 'Campanii Google Ads Swiss Amanet',
    type: 'google_ads',
    status: 'in_lucru',
    progress: 55,
    startDate: '2025-03-01',
    deadline: '2026-04-30',
    budget: 15000,
    hoursEstimated: 150,
    hoursLogged: 82,
    teamMembers: ['Andrei']
  },
  {
    id: 'proj-007',
    businessLine: 'agency',
    entityType: 'clients',
    clientId: 'cli-006',
    name: 'SEO Programmatic NordFinance DK',
    type: 'seo_programmatic',
    status: 'in_lucru',
    progress: 30,
    startDate: '2025-08-01',
    deadline: '2026-07-31',
    budget: 24000,
    hoursEstimated: 280,
    hoursLogged: 84,
    teamMembers: ['Andrei', 'Alexandru']
  },
  {
    id: 'proj-008',
    businessLine: 'agency',
    entityType: 'clients',
    clientId: 'cli-008',
    name: 'SEO Local Dental Excellence',
    type: 'seo',
    status: 'in_lucru',
    progress: 65,
    startDate: '2025-07-01',
    deadline: '2026-06-30',
    budget: 12000,
    hoursEstimated: 160,
    hoursLogged: 104,
    teamMembers: ['Alexandru']
  },
  {
    id: 'proj-009',
    businessLine: 'agency',
    entityType: 'clients',
    clientId: 'cli-002',
    name: 'Mentenanță & Updates Fudly',
    type: 'mentenanta',
    status: 'in_lucru',
    progress: 25,
    startDate: '2026-01-01',
    deadline: '2026-12-31',
    budget: 6000,
    hoursEstimated: 96,
    hoursLogged: 24,
    teamMembers: ['Maria']
  },
  {
    id: 'proj-010',
    businessLine: 'agency',
    entityType: 'clients',
    clientId: 'cli-009',
    name: 'SEO Turism DACH Carpathian Adventures',
    type: 'seo',
    status: 'planificare',
    progress: 10,
    startDate: '2026-04-01',
    deadline: '2026-09-30',
    budget: 10000,
    hoursEstimated: 140,
    hoursLogged: 14,
    teamMembers: ['Andrei', 'Alexandru']
  },
  {
    id: 'proj-011',
    businessLine: 'agency',
    entityType: 'clients',
    clientId: 'cli-007',
    name: 'SEO Programmatic Rute Transport Meridian',
    type: 'seo_programmatic',
    status: 'finalizat',
    progress: 100,
    startDate: '2024-11-15',
    deadline: '2025-12-31',
    budget: 16000,
    hoursEstimated: 200,
    hoursLogged: 196,
    teamMembers: ['Andrei', 'Alexandru', 'Maria']
  },
  {
    id: 'proj-f01',
    businessLine: 'fudly',
    entityType: 'restaurants',
    clientId: 'fud-004',
    name: 'Onboarding Burger Joint',
    type: 'onboarding_restaurant',
    status: 'in_lucru',
    progress: 40,
    startDate: '2026-03-28',
    deadline: '2026-04-15',
    budget: 0,
    hoursEstimated: 8,
    hoursLogged: 3,
    teamMembers: ['Alexandru']
  },
  {
    id: 'proj-f02',
    businessLine: 'fudly',
    entityType: 'restaurants',
    clientId: 'fud-001',
    name: 'Menu Redesign La Giovanni',
    type: 'menu_setup',
    status: 'in_lucru',
    progress: 70,
    startDate: '2026-03-15',
    deadline: '2026-04-10',
    budget: 200,
    hoursEstimated: 6,
    hoursLogged: 4,
    teamMembers: ['Maria']
  }
]
