import type { Retainer } from './types'

export const retainers: Retainer[] = [
  {
    id: 'ret-002',
    businessLine: 'agency',
    entityType: 'clients',
    clientId: 'cli-002',
    name: 'Pachet SEO Programatic + Mentenanță',
    service: 'SEO Programatic + Mentenanță',
    monthlyAmount: 2400,
    currency: 'EUR',
    billingDay: 1,
    status: 'activ',
    startDate: '2025-03-15',
    minimumPeriod: '12 luni',
    nextInvoiceDate: '2026-05-01',
    paymentStatus: 'la_zi',
    includedServices: [
      { id: 'rs-002-1', projectId: 'prj-seo-002', serviceName: 'SEO Programatic', serviceType: 'seo_programmatic', billedSeparately: false, individualPrice: 2000, status: 'active' },
      { id: 'rs-002-2', projectId: 'prj-web-002', serviceName: 'Mentenanță Web', serviceType: 'website', billedSeparately: false, individualPrice: 400, status: 'active' },
    ],
  },
  {
    id: 'ret-003',
    businessLine: 'agency',
    entityType: 'clients',
    clientId: 'cli-003',
    name: 'Digital Growth Package',
    description: 'Pachet complet marketing digital: SEO + Google Ads + LinkedIn Ads',
    service: 'Google Ads + SEO',
    monthlyAmount: 1800,
    currency: 'EUR',
    billingDay: 1,
    status: 'activ',
    startDate: '2025-09-01',
    minimumPeriod: '6 luni',
    nextInvoiceDate: '2026-05-01',
    paymentStatus: 'la_zi',
    includedServices: [
      { id: 'rs-003-1', projectId: 'prj-seo-003', serviceName: 'SEO Retainer', serviceType: 'seo', billedSeparately: false, individualPrice: 1000, status: 'active' },
      { id: 'rs-003-2', projectId: 'prj-ads-003', serviceName: 'Google Ads Management', serviceType: 'google_ads', billedSeparately: false, individualPrice: 600, status: 'active' },
      { id: 'rs-003-3', projectId: 'prj-lin-003', serviceName: 'LinkedIn Ads', serviceType: 'linkedin_campaign', billedSeparately: false, individualPrice: 200, status: 'active' },
    ],
  },
  {
    id: 'ret-004',
    businessLine: 'agency',
    entityType: 'clients',
    clientId: 'cli-004',
    name: 'Pachet SEO + Web Development',
    service: 'SEO + Web Development',
    monthlyAmount: 1500,
    currency: 'EUR',
    billingDay: 15,
    status: 'activ',
    startDate: '2025-06-01',
    minimumPeriod: '6 luni',
    nextInvoiceDate: '2026-05-15',
    paymentStatus: 'la_zi',
    includedServices: [
      { id: 'rs-004-1', projectId: 'prj-seo-004', serviceName: 'SEO Retainer', serviceType: 'seo', billedSeparately: false, individualPrice: 1000, status: 'active' },
      { id: 'rs-004-2', projectId: 'prj-web-004', serviceName: 'Web Development', serviceType: 'website', billedSeparately: true, individualPrice: 500, status: 'completed' },
    ],
  },
  {
    id: 'ret-005',
    businessLine: 'agency',
    entityType: 'clients',
    clientId: 'cli-005',
    name: 'Enterprise SEO Multilingv + Google Ads',
    service: 'SEO Multilingv + Google Ads',
    monthlyAmount: 4800,
    currency: 'EUR',
    billingDay: 1,
    status: 'activ',
    startDate: '2025-02-01',
    minimumPeriod: '12 luni',
    nextInvoiceDate: '2026-05-01',
    paymentStatus: 'la_zi',
    includedServices: [
      { id: 'rs-005-1', projectId: 'prj-seo-005', serviceName: 'SEO Multilingv (6 piețe)', serviceType: 'seo_programmatic', billedSeparately: false, individualPrice: 3500, status: 'active' },
      { id: 'rs-005-2', projectId: 'prj-ads-005', serviceName: 'Google Ads International', serviceType: 'google_ads', billedSeparately: false, individualPrice: 1300, status: 'active' },
    ],
  },
  {
    id: 'ret-006',
    businessLine: 'agency',
    entityType: 'clients',
    clientId: 'cli-006',
    name: 'Pachet SEO Programatic + Google Ads DK',
    service: 'SEO Programatic + Google Ads DK',
    monthlyAmount: 5200,
    currency: 'EUR',
    billingDay: 1,
    status: 'activ',
    startDate: '2025-07-01',
    minimumPeriod: '12 luni',
    nextInvoiceDate: '2026-05-01',
    paymentStatus: 'la_zi',
    includedServices: [
      { id: 'rs-006-1', projectId: 'prj-seo-006', serviceName: 'SEO Programatic', serviceType: 'seo_programmatic', billedSeparately: false, individualPrice: 3800, status: 'active' },
      { id: 'rs-006-2', projectId: 'prj-ads-006', serviceName: 'Google Ads Danemarca', serviceType: 'google_ads', billedSeparately: false, individualPrice: 1400, status: 'active' },
    ],
  },
  {
    id: 'ret-007',
    businessLine: 'agency',
    entityType: 'clients',
    clientId: 'cli-007',
    name: 'Pachet SEO Programatic + Mentenanță',
    service: 'SEO Programatic + Mentenanță',
    monthlyAmount: 4500,
    currency: 'EUR',
    billingDay: 1,
    status: 'activ',
    startDate: '2024-11-01',
    minimumPeriod: '12 luni',
    nextInvoiceDate: '2026-05-01',
    paymentStatus: 'restanta',
    includedServices: [
      { id: 'rs-007-1', projectId: 'prj-seo-007', serviceName: 'SEO Programatic', serviceType: 'seo_programmatic', billedSeparately: false, individualPrice: 3800, status: 'active' },
      { id: 'rs-007-2', projectId: 'prj-web-007', serviceName: 'Mentenanță Web', serviceType: 'website', billedSeparately: false, individualPrice: 700, status: 'active' },
    ],
  },
  {
    id: 'ret-008',
    businessLine: 'agency',
    entityType: 'clients',
    clientId: 'cli-008',
    name: 'Pachet SEO Local + Web Dev',
    service: 'SEO Local + Web Dev',
    monthlyAmount: 2800,
    currency: 'EUR',
    billingDay: 5,
    status: 'activ',
    startDate: '2025-06-01',
    minimumPeriod: '6 luni',
    nextInvoiceDate: '2026-05-05',
    paymentStatus: 'restanta',
    includedServices: [
      { id: 'rs-008-1', projectId: 'prj-seo-008', serviceName: 'SEO Local', serviceType: 'seo', billedSeparately: false, individualPrice: 1800, status: 'active' },
      { id: 'rs-008-2', projectId: 'prj-web-008', serviceName: 'Web Development', serviceType: 'website', billedSeparately: false, individualPrice: 1000, status: 'active' },
    ],
  },
  {
    id: 'ret-009',
    businessLine: 'agency',
    entityType: 'clients',
    clientId: 'cli-009',
    name: 'Pachet SEO + Web Development',
    service: 'SEO + Web Development',
    monthlyAmount: 2100,
    currency: 'EUR',
    billingDay: 1,
    status: 'activ',
    startDate: '2025-04-01',
    minimumPeriod: '6 luni',
    nextInvoiceDate: '2026-05-01',
    paymentStatus: 'la_zi',
    includedServices: [
      { id: 'rs-009-1', projectId: 'prj-seo-009', serviceName: 'SEO Retainer', serviceType: 'seo', billedSeparately: false, individualPrice: 1400, status: 'active' },
      { id: 'rs-009-2', projectId: 'prj-web-009', serviceName: 'Web Development', serviceType: 'website', billedSeparately: false, individualPrice: 700, status: 'completed' },
    ],
  },
  {
    id: 'ret-010',
    businessLine: 'agency',
    entityType: 'clients',
    clientId: 'cli-010',
    name: 'Web Development',
    service: 'Web Development',
    monthlyAmount: 500,
    currency: 'EUR',
    status: 'expirat',
    startDate: '2024-06-01',
    endDate: '2024-12-01',
    nextInvoiceDate: '',
    paymentStatus: 'la_zi',
    includedServices: [
      { id: 'rs-010-1', projectId: 'prj-web-010', serviceName: 'Web Development', serviceType: 'website', billedSeparately: false, individualPrice: 500, status: 'completed' },
    ],
  },
]
